
loginService:
  defaultLoginSelectProperties: #登录默认加载属性列表
    user: id,username,password,nickName,gender,email,avatarUrl,mobile,lastLoginDate,lastLoginIp,isEnabled,isVip,expired,locked,credentialsExpired,extraData,openid,email,logged,version
    admin: id,username,password,nickName,gender,email,avatarUrl,mobile,lastLoginDate,lastLoginIp,isEnabled,expired,locked,credentialsExpired,extraData,type,department,title,version

#日志访问参数配置
access: #日志
  loginByUsername:
    description: 用户(%s)使用密码登录
    saveToDatabase: true
    logLevel: info
  loginByOpenId:
    description: 小程序用户(%s)自动登录
    saveToDatabase: true
    logLevel: info
  loginByUserId:
    description: 用户(%s)访问接口
    saveToDatabase: true
    logLevel: debug